const Homeproduct = 
[
    {
        id: 1,
        Name: 'Kaktus Grusoni S1',
        price: '10000',
        images: 'images/img1.webp',
        cat: 'Kaktusi',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Kaktus S2',
        price: '3300',
        images: 'images/img2.webp',
        cat: 'Kaktusi',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Pahira S9',
        price: '1300',
        images: 'images/img3.webp',
        cat: 'Drveće',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Pahira S10',
        price: '8500',
        images: 'images/img4.webp',
        cat: 'Drveće',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Palma Howea S8',
        price: '5500',
        images: 'images/img5.webp',
        cat: 'Drveće',
        type: 'top',
    },
    {
        id: 6,
        Name: 'Palma Šamadora S7',
        price: '800',
        images: 'images/img6.webp',
        cat: 'Drveće',
        type: 'top',
    },
    {
        id: 7,
        Name: 'Šeflera S22',
        price: '1500',
        images: 'images/img7.webp',
        cat: 'Saksijsko cvece',
        type: 'top',
    },
    {
        id: 8,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img8.webp',
        cat: 'Zamia',
        type: 'top',
    },
    {
        id: 9,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img9.webp',
        cat: 'Zamia',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img10.webp',
        cat: 'Zamia',
        type: 'featured',
    },
    {
        id: 11,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img11.webp',
        cat: 'Zamia',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img12.webp',
        cat: 'Zamia',
        type: 'featured',
    },
    {
        id: 13,
        Name: 'Zamia S30',
        price: '15000',
        images: 'images/img13.webp',
        cat: 'Zamia',
        type: 'top',
    },
    {
        id: 14,
        Name: 'Kaktus veliki u boji S6',
        price: '1200',
        images: 'images/img15.webp',
        cat: 'Kaktusi',
        type: 'top',
    },
    {
        id: 15,
        Name: 'Kaktus mini S4',
        price: '800',
        images: 'images/img16.webp',
        cat: 'Kaktusi',
        type: 'top',
    },
    {
        id: 16,
        Name: 'Kaktus u boji S3',
        price: '400',
        images: 'images/img17.webp',
        cat: 'Kaktusi',
        type: 'top',
    },
    {
        id: 17,
        Name: 'Sanseverija cilindrična S18',
        price: '1800',
        images: 'images/img18.webp',
        cat: 'Saksijsko cvece',
        type: 'top',
    },
    {
        id: 18,
        Name: 'Lizijantus R3',
        price: '400',
        images: 'images/img19.webp',
        cat: 'Rezano cveće',
        type: 'top',
    },
    {
        id: 19,
        Name: 'Dracena Compacta S17',
        price: '15000',
        images: 'images/img20.webp',
        cat: 'Čuvarkuće',
        type: 'top',
    }
]
export default Homeproduct